#!/usr/bin/env bash
# comment
sudo apt update
sudo apt install nginx -y
sudo touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /etc/nginx/html/;
        index index.html;

        location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
        }
}
" > /etc/nginx/sites-available/default

sudo service nginx restart